### ISSUE TITLE
Add a handler for ParseIntError

### ISSUE THREAD

**Issue by caphosra** [caphosra/cthulhu_bot#41]
There are unhandled parser errors.
```
cthulhu_bot: thread 'tokio-runtime-worker' panicked at /.../d20-0.1.0/src/lib.rs:191:48:
cthulhu_bot: called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
cthulhu_bot: thread 'tokio-runtime-worker' panicked at /.../d20-0.1.0/src/lib.rs:195:53:
cthulhu_bot: called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }
```

**Comment by caphosra** [comment]
This is in the specifications rather than a problem. A package [pholactery/r20](https://github.com/pholactery/d20) assumes that a value size is just one byte.

**Comment by caphosra** [comment]
Maybe I have to implement a dice expression processor by myself.
